### ISSUE TITLE
Question about how are you reading the data

### ISSUE THREAD

**Issue by jiwidi** [willhaslett/covid-19-growth#1]
Hi!

Great repo you have there, awesome work to facilite the task for other ppl!

I wanted to ask about how are you reading the csv files https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv 

Looking at your function
```python
def df_from_csv(file_name):
    df = pd.read_csv(file_name,sep=',')
    df = df.rename(columns=constants.RENAMED_COLUMNS)
    date_cols = df.filter(regex=('^\d+/\d+/\d+$')).columns.array
    df = pd.melt(df, id_vars=['province_state', 'country', 'lat',
                                      'long'], value_vars=date_cols, var_name='date', value_name='cases')
    df.date = pd.to_datetime(df.date, format='%m/%d/%y')
    df['day'] = (df.date - pd.to_datetime(df.date.iloc[0])).astype('timedelta64[D]')
    df.day = df.day.apply(lambda day: int(round(day)))
    return df[['date', 'day', 'cases', 'province_state', 'country', 'lat', 'long']]
```

Seems you read directly from the COVID-19 repository you have linked inside the repo, pointing directly to their files like `https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv`

But when I try to do so with a simple:
```
df = pd.read_csv("https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")
```

I get the following error `Error tokenizing data. C error: Expected 1 fields in line 33, saw 2` 

Any help on how to read them directly? Thanks!

**Comment by willhaslett** [comment]
Hi there. You can't read files directly from GitHub. You're passing a URL to a function that expects a file.

**Comment by jiwidi** [comment]
> Hi there. You can't read files directly from GitHub. You're passing a URL to a function that expects a file.

Nvm it was a mistake on the url to the file! 

Actually you can read csv files from url since pandas 0.19.2 (and we are in 1.0 right now) by just passing it as filename (see [link](https://stackoverflow.com/questions/32400867/pandas-read-csv-from-url/41880513#41880513) )

My mistake was I wasnt using the right url for the reading, I had to use the raw github access to the file.

This now works:

```python
df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")
```

**Comment by willhaslett** [comment]
Great. Pandas is so slick.

**Comment by jiwidi** [comment]
With this hotlink you could actually remove the need for the recursive repository? I will be happy to fix it for u in a PR if you see it as a good change.

**Comment by willhaslett** [comment]
Thank you. I like that idea, but I want to leave the submodule in there for now.

**Comment by willhaslett** [comment]
After more thought, the benefits in simplicity outweigh the costs in terms of versatility here. I will implement this later today. Thank you for the suggestion. Opening an issue now.
